#!/usr/bin/env ruby

require 'nokogiri'

file = File.read(ARGV[0])
doc = Nokogiri::HTML(file)

stylesheet_link = doc.at_xpath("//*[contains(@rel,'stylesheet')]")
stylesheet_link.set_attribute('type', 'text/css')

File.write(ARGV[0], doc.to_html)
