#!/opt/puppetlabs/puppet/bin/ruby

$LOAD_PATH.unshift('/opt/puppetlabs/puppet/lib/ruby/vendor_ruby')
ENV['FACTERLIB'] = '/opt/puppetlabs/puppet/cache/lib/facter'

require 'facter'
require 'json'

fact = ARGV[0].split('.')[0]
project = fact[/(.*)_version/, 1]
component = ARGV[0].split('.')[1]

if component
  result = Hash["id" => component].merge!(Facter.value(fact)[component])
else
  result = Facter.value(fact).map { |comp, version| Hash["id" => comp].merge!(version) }
end

puts result.to_json
